---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-secret
  namespace: sa-p6
  annotations:
    sealedsecrets.bitnami.com/force-managed: "true"
spec:
  encryptedData:
    url: AgCwOIMht43yarv2YflZdIsFCxTVEhFsYJkOxRtOCsTvTeIKouY/RcHpoAqt2oPWctnnqdV/2b2PtoJf4+e9Ag5betmT4QANn1waOe0MpD8hlS8RIWCFCcbbUrSQrZUUySPPQJ59EptZqirZ8yRcdrmo20XLlEcJOUermnY2Lt6JnyqnfpavBqInijvCH9zEpH0D4WrmyqLx4fl5DZFlXUTaAB4Uj1j6u4zzUi+QAMfJN2UnshEJfsCxGpSBGUPW09uRgOGjGjvRxdd09MQLqQx1g4XO8lL8jXQQ5t9Vxaa3ST+Xn8jhOXcmwJiBeBiVyiu9C5fn95ah9F+nU7xwGf681y3vxiRlzy5QJspcGQc1nTiIY4Xw+1nUH9Yh3Loli50Kj07xwXS7CW39c7cFRVd+41n7cGIZCK/569CRgRJTruiU/6jzjzgs8evDCuJFQI4SpJuj+MFksEHcX31Inp4A9lha571NQGi046GuJVn00b3FEJ6rNyOWa78G0rwJh/5TbGMMbPYs5Fw5ivGsjcpFYaCQxYNMLCShlBzcFwlO5plFbU+HHllhrMb/cBEh9BN42nwu1gBAzJGLQZ9L4Ru3PrQNKtdZMRXFeP9S6PpK5sKqOuSv0n+8fippKgISGcQ5kLxTsdf3XHRhRT/T35O2me9Cs6I04DG3TQhck5S6ifCiT0rC/qocXNdnmHnFNmiwOZujU3COU6puhCqoRBbbZbZdBU8WH6pApiEgKk4rShJmwF72rWbqFLNHtEeCzIcUYsMpTUA/3O0ydgZ4h8ISAP6nadlvdwPF/pjCzbFVnZYI3sBeJFXHKTO5FeP5+NO8o3J4DZSH86PaSdFx46hdZ57zpvMH6DsjtoNs5iyHuidHmPlADNX1RY1pq9lr9KbT61k=
  template:
    metadata:
      name: cronjob-secret
      namespace: sa-p6
    type: Opaque
