---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCYQCOomgRVprfzlfMIu9EI3PKY1bp2OvWe/RISm6uLwZeLaTtWZx79zcrRgd2F77aNroTPsNb5yIAfeN5x4xftKEWZWcEd/PIIbW2ntDV1+QIisJDmG9tsCKv08pVyj4MPDfa7yJfPyJV7vjcBg0dWmWEjv6MVfPtm7mo2fKGGvdtbCRtYi4DDs5PqXEPPGLAXl0em6rbL3eCeMiF1CrMLzL3vBSn9NcDEPMfS0tuoyEACoZBlQgRNVSmhQ4LJZg1HIEsM7zvB2e0WgTGqsobRg1cRWh2FM7C4odQxZLFXTqTiTEaBy1YzeXwD3xUGB8RSFZ0y8h2zXkmAwLbfXggFz/dGUp0f2pHesN9f5QDL+9XjFIIbaRFacfI4+KkuXbVjVt55D8J4Bdz9sCVsJ3DHhssQ7GJnA+4iSKEClzqwfOh8uSSSSB2FLQrhqOVETxxGtvORvhVYOkVew4DCNj3XPLdmFuU4X5N+TYMaoUAzODj+KMZz66KI003Ug5Ex7xQjMo7hB7eNhk6fnDu+sKPJo1DLPnpUc4HUgYXhcKhTwaWaiz+2UJC58POo8ucyH7WeHRwY2Eqv96o1fHFCP2yvNjwwhHoGRfg73deSVhJln7bJPfudvMAZDInPbAVWoz6dopxSm7c2qv9aHQ0gyqbeQFlwrll/ZltrbwsNJnvJDUZXjp3p4mSnPkxNohR1fRTSWCnhxYt2HFcILAj5ErJX5bZk8jBYjen/0PL5/9EtgRvfS+U3gpSywGu6kL0qNtU8ZLbtI+rVipvVfUdQzEce+EHJe7wQ/q7uTxx0JcxZif/Fz+XsP1Ds2UhAzBWNAEkBA4m23XgrhF+8F/AHK+S5lkAfR5R0TN4l8YmadjbKB7O85QjlZf+cYOalaDpy0f6A/mK2JF1wNmukeQGfJb8Iu/mtK739KmFSNgY2yxXk7AjWmFEujZe3zvxnX0WDowmlNsQ5wuHSd0Bk9gzSAcKegzkAJ60=
  template:
    metadata:
      labels:
        velero.io/backup-name: sa-p6-daily-backup-20261004202306
        velero.io/restore-name: sa-p6-daily-backup-20261004202306-20261007155506
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
