---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: sa-p6
  annotations:
    sealedsecrets.bitnami.com/force-managed: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgCCHPxK4fTbOJJ3U5cg3TsZ3WEZOgf8/PsRP6K2kg5n7q8KYtnFaPlwswhXxkAHUwOpcQURZUdmDTf/SPaiaLxcu6t+oSo+2PcuMYVAMw4fgTbZHmTiGIgOPUD/At8g0OrSEJHvM6uzFXweitQM2MEOzykNqvxe54dtafOf3SqGQazU6gtgqVYXOcOkbGL1+nKWGEMs0b5imxmHmkCuWkM6wNwiKHeGjikEeNJqs+LJ1qq3vOWDxohatHrqW+MfLBe1SYHvJCpB4RB3lmcZVswf6da+E3YGsrxULoBajx8hhuMx9mTgx+bQRNmy46Tx1psZAXIcMEwkkfXA/QCeQCJOETTv0a9Z7uCQA508uke28pxVa0XiEIckrlqzeM7bYCZqCEMpYglDkQ9pNZK49fH3gZMCBs0gCT7M4N7Z2d8j5cJQiSyVWJcearj+XIFnvYE1LMuffuckd7/c4PqGxTSPSGev21qAnQIS326rDEa041xpR97ArLlnrJtXLNXWzwbT3j/E9GZoBK/rUmlLFK2G3z7yPiP0k3Ru/iCltQ92IQE/TimqYsPnWVBFPyoKV/OvMZorTiNEQ9ZsP/OwzlBKUDLTzPDmoiAyq2cMnjkxRUXLnGTRlkC30ouW7VLXoM+MJwxRfD/1qfIs8EEWzXUy1y4TMDoHftoV46m/nF/6EGJd2hBGMLam2AhJ0GdoDvEiX3ybQt46oI+vC1sbt4Wn6VNxMqyh2ZTPR+DzQHOdmCF7pgWJwKJdH8ut8iGNicl91Ob5F1AcxI5DOoveTYx2pCysCh3ldfGvWoekyKA2kSn8VPvHn24EKunKibCJLu5dKmlTQVsxPGedWxW9KOUSLiN7XAXpyGwaxxLyyh7vauvMi2L+xxHin9chS365m0H8Ms1PWXkNXK8rTM9Sr604F9GIsdZdGmPP0FGBKeuixBoIkCjgd45Rjjw81fdXi+hoWJujmuxg7eHo+js91Nh5fqwqvrk=
  template:
    metadata:
      name: ghcr-secret
      namespace: sa-p6
    type: kubernetes.io/dockerconfigjson
