---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: sa-p6
spec:
  encryptedData:
    url: AgAlrySCZYsQsrkC2zWB/9UbK3jHwOoGgGJBUTt33dTRgtb14TFWHMpt+8Q9lIxqUV7hZprsKgAH3oxuC+D+3eDESWiQyMx6I4qTMKS6JTxc4WfwHxAnrpT5ATpkWIIvsouB2qvgb+Ofc1JueolQzFP+cy/v/v1ceEMUIK2hB+w5ig8J4o4Bao9xqZuS5+MM8ngeARoTTZrT+xTej4BG520GvQT0a+xjEw8JNxjzRKzLb4vumZzsFPH1vAtO7AGVowGdSamTeB99r7WPWjO3KwFtgD7TcHSUtWQLGs9TlIXWSH3aH96ACjAIcyYfIG1O2uEwkjQV8EqjPozS0DpP8QtwaFzKDQ8nNX0uvnmXwKSfcrlWDyTas9G63g4HeqsAa59zzBkecjB+RQdDzULZpGdBfEaCPrWg/yYHBK07GpTjDIGeAAnjnLs0atcrwT45ca1fKSjohUsoQa9Lfs8ttNxV+YCuqohv88mI3ASnjXCjf18SCQU3cOevmYuD1/GCogCif/j1zUHYgIQnfmHy7k4DH72xMwpimJQgGykKWGElf6nRah+PCRyoABFrn/L6FZbUfugx7ijF8XMeDEIiuXpfJJS25HXOECNQBtOzXTZQukRrq/Mnk3AagN7G2IG2VuD/0oISU19NCqVA3BhRbXkMy2S3nX/gLbR8vklgOE3B1RzYZ1wN9y+0MilUTnY9OnBG3pi+UyypVhpwIs1h5rlOLtRg39y3U0CWDn60T0oNaR1ImQ8DOmSqQP8diEz1whkZN2EKh6vJLBa8sdlqArBArhRjzRx8FYU5upHIORtVng80P5FH+kK0tvcS2a4i3QZ1CD2Ldc0Vtd4j6l3um47W
  template:
    metadata:
      name: mongodb-credentials
      namespace: sa-p6
    type: Opaque
