---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: default
spec:
  encryptedData:
    url: AgBDz5wFKpGxar/h4ISPNfPB03nZI/tIs2KGNDqqE8xZrUg9RZSToWFLS/hDvMGRerzhS5EPITg1LpLJEwys9mu4/voS11+BaaoTEUGk8nbZ+XT2HBKaO0asloyVpIKTT2tZL1C4fSYraxeQDCbFFdRuhiOp5Bt1N2IdyrWksDIRf41+jG7lNQFhHC+raBz7YCfhDpVeZ0aLrd6yuLfPqM+1Ai4Y4WXVIFOLgW5OcS+Ud1EIeE9Yumg8o58vKUObMgSwCXuJXXJYUXsvAByN+R7KNVSpczLRhVrjEDBbpy3o7nmkaAVQQqQ29NLxm1myM79Cp70pmynZ02ln/6Te3od2zIsMXOA7GV4Itmrbcsytwm65V6qi4fPGYy0QtCfyA+l8VtzuPhCQULAEiIX+NADLQTNXxEskrmHlOUIM9H8o6UC8fcWxX6Wn5POYSbpB3j/DRaJPsxORvkJCtgO0/uX0eLh4ZOD6jdtY3JPghmalV9jDmig3bG+8orLa2zqMGSA77Y+6vZJ2N408A1iPnLejjXUCVd8njd0aV19qiu1uvfly67wzoQKIzpDYy8+PpAuv140W1wIOhD/xt6G8bitFU+X03M+laxAIAQ4szZ2sdBnqPyj7n7PMtvdUMmUZsY80Ry4aXUp2IUm+ItV4J2Lrd58+nR7e83HfB7qctePr+LymwLlcJe0r2S9j0Wfv6EUfXW6Uq2waG3TTKcPo1YswjbhPT17PMLWwMQpYHNXV90pMpMPEGKQwlsojm3spYbWSqJlcAfbCS4fJxIMGVExUJJ6qYee4+mYmsAzi8ZcOL/5ZpMwUvCiG3m97Kzi+yEBVjtgsmwdqzmpIxFKS3hYt
  template:
    metadata:
      labels:
        velero.io/backup-name: sa-p6-daily-backup-20261004202306
        velero.io/restore-name: sa-p6-daily-backup-20261004202306-20261007155506
      name: mongodb-credentials
      namespace: default
    type: Opaque
