---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-root-credentials
  namespace: sa-p6
spec:
  encryptedData:
    password: AgBKBXrL+Z7gFDM5lKjEE2t+ZL2wg/YFMlcjYySgcFcN5fPJCQa6fLdOtXPDSuZl2/5lxtpo5go6+rbnsDDgZWjL7b/uMqawCmYOdxXkR9NJVA310nEgSE9Fbf8ET1/TugkY9fXo2ZgRA9/twDAQfzPfUK/pplEDZOGzdAkYrQn2QylXDtwjvbxzXG7XAiydNXQ0fZP1WHWbOiS+gxnkybgJmm225JMSdkaUlN9f6cwrtyUfnVpAz3KK1GBL/m0bFN89aQe3u4rOElPET8HV2vE+nlMIRqx++H/1Z6qcPuTaBPXB6dk7K4Akn97RAVp4LMUUjJ36v6MvQEdwS8WK34PrkkcWirfZPT6acvr33gMYM3SmMnDCgF+o8hGAVT9dFAAuQ38eKjdF/AzqG/RRAJ1SCFWswgEIWk+kbxlilZSn7LikdpuS19oEno2UFKnFsCAqgYpXMsQljvfWO/Bj5FTWZ2p5BEubvSD4t4E9rZ7ykWwRAfIREi+RJMRFV7AaswrTnBVlmi21hZtk8cMIEbKzL405I9Y+KPNsgx6KdlmI04yYiY2KvfddgrGHJQjWJnyuLD2UMKpgDo7PwTruS0WKEAgJAcTjLTNmwbiKnQt/XLQASgspgJBcSeFjO0jDnCCy9ikPeNn4WcoNycZ0JuLlsXNJ/B/GapJLJkaRszGcoWG88w25ZSK6iyI/rb34dGSNp6MNbnE92VxPZgTF47QJdzRpW+cNEvcv0ogWBE7rdL5i
    username: AgAJM4SzqVVKFqjUqsOdCS9in2rPTGg5LQ7KfUSj86BzSVShfbbY+L0dWnsW7iL9nLAuS63F58+raUL1wqAkvoQHNzIYcHelKFLMODN9cVKldi0VUpJrt0728h06aH8/wObm9iwQPMRWVEtbOZqUU7Yww4QgUHYAk7L7wDL41YmrdZGLhSdHkDKO+pCmzCK/n5UP3ixIpnweXPo/8REsaZbvYwZHmeMFk5hND25+2JuL0VPghgUaq16lHVNxouzaCjOg20F/A58qTVyTVnns8DiyWnh0p2+z9D4SchV8zH0g0wV9YmhjwZEetBfLnm4i0AMziWT8ioDjK2b1EW9NawRG9Fe5fMmd9h1WZomBwSM9lWUahOUR0cAO2DRieOGbw2ZjUfo0sKKSqTbipQ7WxqIu5/1P7Y6AOe6IXhTqW9wNOftI2sLSvElAbfZ0QIpkhu/512+4AIJmaBexRGHySf7zkcr/+Igpv/3uvfOm8C1cqP+ranN1AgrtX/P0gsRB2MUqPJjcF5h10iW/3agd4cvFQg7zYBoGelx+P9a9JN0whxhQVo6L2VJxku5kqMj6bWk0kyDOrWMqcQIt0h+VR5UXLHjzNe9OFhyytCjoWxztaV/vQTmgNXs/1HPYjstN1RDfJJoOhHZefKSEXYxV6k36zRu2AVpbRUEBlHBKThseCEjW8Kw3mAF4CAK7ylhZY4FLiPew
  template:
    metadata:
      name: mongodb-root-credentials
      namespace: sa-p6
    type: Opaque
