---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-root-credentials
  namespace: default
spec:
  encryptedData:
    password: AgB1O7eE/fAunvaMwvw/p9KICZ6aB0dDxEn8Uy4L1BQdn3Mqf3pfwvdp+NwKJG7BUNxlURiP+jyuByzxO3nqLlo2uOPH16hpHFmCgVqFeEyopCN+Ljuom+V0JsCStTiwr2djkZb6SNDAm66rNQZb9xuIED2VvogRzCsudCxubga5PevzNn2BQnQmH3AtFJybmxAanmWCiZFFu35cTTmtiCiV5WwZ2QRFYWEgjzlPSQranoxig8MliZApD9f7UjWNFgTFmkDg33bNZGL4Al9IvNBr89ANju6A09174OakJYBmgBALTV+DWmldP3Q78y49/XTJV1dqo+bZAYGRRufO6V6Lb6jtdBgHvkywRHairdZYradMYLIk9jDVcVJKBt79cyndDgthzWA+praxSJnzyslRU33IWRUC9Tu8abxZTUULf0k1CipfNptUWXSzXWgJAp3qrQwGBFoCSG26Bn0gpn9PwMK5vJx8ldzrtBHZ+camKIpcoQo0Xrp6guZ7fQcZMvT0mxLgazZI+Ia1uc2/dtOf/OA4PQKVqjw6IOuPjacqNUHahsCR67ur2k6dX2ob8D8qUa8vEJhM88pMiehuMRQ44AtjrP2Dg9Pl8kh8mY96k9bnB1GO7bdaBON2v0Nv5ELxiuoQXbyBjo/y1NNzK7l7vM62CLlwRcDK/bwsFrgvNwq1iyB2d9q50KHgeIebX8oZjvDt/NDYFz/3/m+y0hdGNiAbZX5uaIARMsBIoyuAEOZe
    username: AgAWbKyVgm9TVJ4GlAgPo1A85CCBuCrYKZWl+JQEoMmSCcgr4xVuhax/o877GseEev61mn1pdmm39VSPcsV+oWCRfUYMsDFFGx5+II/sphKt/O3s3CqU7q4sCYb5gKA23VxnI3M2WA/IlNALEmM5D9vh/MDfbSUuGFaytgx5pxEZL/956MELLFLux7sjNIebIUcryNKPrwFcttj54JqNL+D2Yf4/E07JXik5e9D+66W10Ha9kHCNeNOke+qENl9ZJ1e36YUpchgFc8WqmQKbrijKPlDCH183UQaAlRxB2jSw5OBaQ77TGzuGDZiMlTHulOVYBZN517QrVZx9cRev4VZ8LAnt9MdUrpQyEyi/VYAsuscJfXmPNj8AFteZ00BG4qGIAXAW03GCp/pDQeOEEEWZnHKLDhyYbDpuxriC+y6yaGHLhqWpMPS+l7jS/MIcjxZYSfGQVKHOpJvE2K9BejBi/G5EMmuxwInCPiN0I1ezVeA5w7j0s03++wWZn7gCIZh+Av2H2KigR7g6k94A4y+zFI0A+Fizo7Egj6XC+7Uta3ZLHBYRjVZoJqOh8ZnemoWfENsVZnCg+0GhHg8VYgMgXN/g29/GaQGswONcWYTzj8gvaPnqJxLb5j/QymzU1jfbFC534kfRJHpMYan74+IvqSK+EI3fkZnL6LdrrlBK02omUQMRpEqkgGFeGfxagR0Dimsa
  template:
    metadata:
      labels:
        velero.io/backup-name: sa-p6-daily-backup-20261004202306
        velero.io/restore-name: sa-p6-daily-backup-20261004202306-20261007155506
      name: mongodb-root-credentials
      namespace: default
    type: Opaque
