global:
  environment: "prod"
  logLevel: "warn"
# Tags de producción — los actualiza el PR automático del pipeline
# Usando v1.68 (existe en GHCR, construido por el pipeline)
api_gateway:
  image:
    tag: "v1.68"
auth_service:
  image:
    tag: "v1.68"
sensores_service:
  image:
    tag: "v1.68"
datos_service:
  image:
    tag: "v1.68"
alertas_service:
  image:
    tag: "v1.68"
# ⬇️ NUEVO ⬇️
api_gateway_proxy:
  image:
    tag: "v1.68"