# Service estable
apiVersion: v1
kind: Service
metadata:
  name: datos-service-stable
  namespace: {{ .Values.global.namespace }}
  labels:
    app: datos-service
    role: stable
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      name: http
  selector:
    app: datos-service
---
# Service canary
apiVersion: v1
kind: Service
metadata:
  name: datos-service-canary
  namespace: {{ .Values.global.namespace }}
  labels:
    app: datos-service
    role: canary
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      name: http
  selector:
    app: datos-service
---
# Service principal
apiVersion: v1
kind: Service
metadata:
  name: datos-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: datos-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: datos-service