apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datos-service
  namespace: argocd
  labels:
    app: datos-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AJCG03/gitops-sa-p6-202201130.git
    targetRevision: main
    path: charts/datos-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true